### ISSUE TITLE
Anki 2.1.45alpha has disappearing Preview button with this add-on

### ISSUE THREAD

**Issue by AnKingMed** [Liresol/anki-custom-shortcuts#113]
I'm unable to actually get any errors, but I can very reproducibly make the preview button disappear by toggling this add-on on and off.  Unfortunately making the preview button go away makes for many problems...  I mentioned this to Damien (maybe there is a fix on Anki's end?).  If you could look into it I'd very much appreciate it!

https://forums.ankiweb.net/t/anki-2-1-45-alpha/10061/76?u=ankingmed

**Comment by Liresol** [comment]
Hello,
Just pushed out an update to fix this.

Looking at the code it seems like the devs are trying a new method for setting up the windows, so shortcuts there are probably going to be a little broken for a while (e.g. it looks like the preview shortcut can't be customized). 
I'll look further into this when development settles more on how they want the code to work, since it seems like shortcuts are currently not exposed but could be later on.

As always, if there are any other issues, let me know and I will see what I can do.

**Comment by AnKingMed** [comment]
That fixed the preview button portion for now. I'll keep you updated if I notice any other issues. Thanks as always!
