### ISSUE TITLE
Editor Cloze Alt works the same as Editor Cloze Edit

### ISSUE THREAD

**Issue by krisshadow** [Liresol/anki-custom-shortcuts#138]
These commands work on their default settings, but when I changed `Editor Cloze Alt` to "`Ctrl+S`", rebooted Anki, and edited in a Cloze card, it worked exactly the same as `Editor Cloze`. I then tried the same steps but changed it to "`Ctrl+W`", but no luck. Same with `Ctrl+R` after I set `Editor Remove Format` to an empty string. 

I made sure these keybindings didn't appear anywhere else, only to these commands.

**Comment by Liresol** [comment]
Hello,

Sorry for the confusion.
The functionality you probably want is in `editor cloze no increment` which will never increment the cloze number (and there is also `editor cloze forced increment` if you needed that)

The reason the shortcuts behave like this is due to addon compatibility, since in the past `editor cloze forced/no increment` *were* the `editor cloze/cloze alt` shortcuts but this had bad interactions with other addons.

If you wanted to know how `editor cloze/cloze alt` work (since both actually work the same way):
If the shortcut contains the `Alt` key, then the function will not increment the cloze number,
Otherwise, the function will increment the close number.
