### ISSUE TITLE
Change editor Cloze alt but not working

### ISSUE THREAD

**Issue by KeenanQ** [Liresol/anki-custom-shortcuts#163]
![Screen Shot 2022-04-26 at 8 33 05 PM](https://user-images.githubusercontent.com/104474694/165420423-87cdff16-e0fb-4482-9004-b10ddd4394c4.png)

I changed the editor cloze alt to "Ctrl+Shift+D" and I changed the reschedule shortcut from "Ctrl+Shift+D" to "< nop >" (w/o the spaces). When I use the Ctrl+Shift+D, it does a cloze but will continue to increment instead of keeping the same cloze number. 

Any help is appreciated! 
Thanks!

**Comment by Liresol** [comment]
Hello,
Sorry for the inconvenience, but due to compatibility issues with other addons, the function of `editor cloze alt` was changed a while ago to be the same as `editor cloze`.

You should be able to get the functionality you want from the shortcut `editor cloze no increment`. If that doesn't work, that is definitely a bug, and I can try to look into it further.

**Comment by KeenanQ** [comment]
That worked, thank you so much!
