### ISSUE TITLE
2.1.49 - "F7" shorcut for set text color doesnt sets the right color when pressed

### ISSUE THREAD

**Issue by SoftSalem** [Liresol/anki-custom-shortcuts#165]
It will alwas set a #0000ff blue color instead of the one that is showing in the editor
![image](https://user-images.githubusercontent.com/104769180/166231469-7d0a1ff2-5a6f-473c-877f-971de865b0ad.png)

**Comment by Liresol** [comment]
Hello,
Sorry for taking so long.
I've just pushed out an update to patch this issue, though I'm not satisfied with the current solution so this might change in the future.
If this issue still persists, just let me know and I will look into it further.

**Comment by Liresol** [comment]
I've changed my mind on this issue, since it's due to a compatibility issue with the new editor in Anki. The behavior above will return after updating the app again, but this issue should be solvable by setting `editor foreground` to `<nop>`.
If you're still encountering issues with this, let me know and I will look into it again.
