### ISSUE TITLE
  "editor foreground": "Ctrl+Q" doesnt work anymore

### ISSUE THREAD

**Issue by BrownJason44** [Liresol/anki-custom-shortcuts#167]
tried Ctrl+ something else as well. Seems not to work anymore since the update.  "editor change col": "Ctrl+W" works as always. Really really depend on setting text color easily (and not via F7 / F8).

btw: love the addon!

**Comment by Liresol** [comment]
Hello,
This was due to a recent change in the shortcut as a response to compatibility issues with the new Anki editor.
I have undone some of those changes, since the solution to the compatibility issues can (for now) be done completely in the config. 
If you're still having issues, let me know and I will look into it further.

**Comment by BrownJason44** [comment]
wow you are quick! thanks so much. works again perfectly. you saved my study week! Keep up the good work <3
