### ISSUE TITLE
Reschedule shortcut not working

### ISSUE THREAD

**Issue by docdd6** [Liresol/anki-custom-shortcuts#173]
Hi there!

I just updated my Anki to 2.1.54 Qt6.
Some of the assigned shortcuts are not working since the update.
For example; the default shortcut for Reschedule is Ctrl+Shift+D, I had it changed to Capslock.
It’s not working now. I even tried to change the shortcut key but still not working.

Please help.
Thank you.

**Comment by Liresol** [comment]
Hello,
Sorry for the delay in getting around to this.
Could you specify which shortcuts aren't working and which alternate shortcuts you have tried?
I am trying to figure out where the code could have changed this (and changing `window_browser set due date` on 2.1.54 Qt5 works for me, which is weird). I'm also not sure that caps lock ever worked as a shortcut, but that's not the main issue here.

**Comment by docdd6** [comment]
I've tried changing `window_browser set due date` to 'g', 'q', 'w' and changing `reviewer set due date` to the same and different letters, trying every possible combination, changing both the codes alone and together, but none of them seems to work.
Capslock worked fine in the previous version of Anki.
All other shortcuts that I use are working fine.

**Comment by Liresol** [comment]
That seems to suggest that the shortcuts are completely disabled for some reason, but I still can't reproduce the issue.
Can you try the following actions to check what part of this addon might be breaking?
1. Disabling this addon and testing the default shortcuts to make sure they work
2. Enabling this addon but (after backing up your configuration first) resetting the config to the default settings and testing the default again
3. After manually setting `window_browser reschedule` (which I misnamed `window_browser set due date` earlier), manually right clicking a card in the browser and seeing the "Set Due Date" text (in the screenshot below I set it to `Ctrl+G`)
![Screenshot from 2022-07-15 03-44-41](https://user-images.githubusercontent.com/16006418/179208508-c4929d81-0638-4e12-925b-c4c1fa9a2122.png)

**Comment by docdd6** [comment]
1. Default shortcuts work completely fine when this addon is disabled.
2. Enabling this addon but setting it to default, all the shortcuts work normally.
3. After manually setting `window_browser set due date` to Ctrl+G, it appeared Ctrl+G on the browser but did not work on the cards while studying.
4. But then I changed the code `reviewer set due date` to Ctrl+G as well and now it is working perfectly fine.
![number 1](https://user-images.githubusercontent.com/108472567/179230701-99bbb1f2-191b-42f7-910e-802431f32bd0.PNG)

**Comment by Liresol** [comment]
Ok there are a few things that might be going on here.
First, `window_browser reschedule` is responsible only for setting the due date while in the browser and `reviewer set due date` is responsible only for setting the due date while reviewing. This would explain the behavior with `Ctrl+G`, since the first change to `window_browser reschedule` would work for the browser but not change the shortcut in reviews, but changing the corresponding reviewer shortcut will change the settings during review instead.
Something else that I found is that there is a little "bleed" in shortcut interactions which isn't yet detected by the conflict detectors. 
Namely, `editor` shortcuts and `browser` shortcuts can conflict, as well as `reviewer` and `m_toolbox` and `main` shortcuts.
This might explain what happened earlier when you tried setting the other shortcuts to `g`/`w`/`r` if you had already set those shortcuts in other places.
For `CapsLock` specifically (which I did verify is somehow supported), I found out that my keyboard can't type `CapsLock`, which is annoying for figuring out this issue. However, unless you used `CapsLock` as a shortcut in more than one place it seems unlikely that this key specifically would break based on what I'm seeing from how Anki is behaving. 
The only thing I can think of to test this theory at the moment would be keeping the default shortcuts but setting exactly one shortcut to `CapsLock`, which I would try if I can figure out what's up with my keyboard.

**Comment by docdd6** [comment]
When I checked the keys `g`/`q`/`w` for `reviewer set due date` and `window_browser reschedule`, I made sure there was no other shortcut using those keys. The same goes for `CapsLock`. I even tried setting all the other shortcuts to default while checking the `g `/`q` /`w` keys.
I think this new version of Anki needs a `Ctrl+(key)` format for the `reviewer set due date` and `window_browser reschedule` because I tried `Ctrl+L` and it too worked. But `Ctrl+CapsLock` didn't work. (maybe because such a combination doesn't exist)
A single shortcut key for the above-mentioned shortcuts would've been easier as it was before but if the new version doesn't support it, then `Ctrl+G` is fine.

**Comment by docdd6** [comment]
I agree with you. Only some of the keys are not working. 
I restored all the shortcuts to default and assigned `CapsLock` to `main browse`, `reviewer edit current`, `window_browser reschedule` & `reviewer set due date` one by one but none of them worked. 
Then I assigned `G` to `main browse` and it worked but did not work with `window_browser reschedule` and `reviewer set due date`
I just tried `J`/`K`/`L`/`Q`/`W` on `window_browser reschedule` and `reviewer set due date` and they all worked.

**Comment by Liresol** [comment]
`G` in `reviewer set due date` I can probably explain with some existing shortcut in Anki that I can't find right now, but for me setting `G` for `window_browser reschedule` does work, which is weird. The only thing I can think of for this is another addon using `G` in the browser, since there isn't anything special about `G` specifically.
The `CapsLock` issue might be Anki-wide and possibly unfixable if it's inherent to Qt6, though I can't really see another reason it would work in a previous version and then get removed (and it still accepts weird shortcuts like `Tab` and `Left` (the left arrow)). I've been too sidetracked with other stuff to get simulate CapsLock properly (or find another computer with CapsLock) but I would definitely look into this more once once I get that figured out.

**Comment by docdd6** [comment]
Yes, `G` does work for `window_browser reschedule` for me too, but what is needed is being able to set the due date during review and for that `G` doesn't work. But there are plenty of other keys that can be assigned. Due to my lack of knowledge, I could not assign other keys to the shortcuts, but with your help, I did that. 
Thank you so much for taking time out and figuring out the problem, explaining everything in-depth, and solving the problem. I sincerely appreciate your responses. I wanted to have a single key set for the shortcut that I now have because of your help.
