### ISSUE TITLE
Possible to have duplicates for undo?

### ISSUE THREAD

**Issue by vykarious** [Liresol/anki-custom-shortcuts#19]
Hi! Thanks for making this add on for 2.1. I've successfully added other duplicate shortcuts for reviewer keys, but I was wondering if you know of a way to duplicate the undo key. I'm thinking primarily to bind it to 'u' in addition to 'z' such that I'm able to easily use my right hand to review. Thanks!

**Comment by Liresol** [comment]
Support for having duplicated shortcuts in the main toolbar has been added. The relevant portion is in the "m_toolbox _duplicates" object ("m_toolbox undo" is the undo function), which behaves like reviewer shortcut duplication.

I'm also going to leave this issue open for a few days in case of bugs so that they can be addressed in one place.

**Comment by vykarious** [comment]
Amazing! Thank you!

**Comment by nicktohzyu** [comment]
This is still pretty confusing, can you please provide an example of how I can duplicate "reviewer suspend card" to both "@" and "+"
