### ISSUE TITLE
[Feature Suggestion] Save Current Filter…

### ISSUE THREAD

**Issue by schmidhauser** [Liresol/anki-custom-shortcuts#52]
Would there be a way to make the menu of <kbd>Filter…</kbd> available? E.g. something like the following:

`"window_browser Save Current Filter…":"Ctrl+Shift+Alt+F",`

**Comment by Liresol** [comment]
Sorry for taking so long to get around to this (and implementing something other than what you wanted anyway), but I have added something for putting custom text into the filter with a shortcut.

You can now paste text into the toolbar with `"window_browser _filters"`, where you can insert custom text into the search bar with a shortcut, e.g. `"is:learn": "Ctrl+Shift+9"`.

I will try to get to what you actually described this week.

**Comment by schmidhauser** [comment]
Awesome. Thank you so much.

**Comment by Liresol** [comment]
Just pushed out an update that also adds in saving the current filter (`window_browser save current filter`) and removing the current filter (`window_browser remove current filter`), which I hope is closer to what you wanted, since the rest of the menu is user specific (and is hopefully addressed with the `_filters` stuff).

**Comment by schmidhauser** [comment]
Great. Thanks again.

I also reviewed it (with a few examples) on https://ankiweb.net/shared/info/24411424 to give others a taste of the changes you just made.
