### ISSUE TITLE
Combination of Search Terms

### ISSUE THREAD

**Issue by schmidhauser** [Liresol/anki-custom-shortcuts#71]
Under the attribute `"window_browser _filters"` it would be helpful if one could use two or more search terms. Right now one can easily switch between various options if the search terms are simple; but if one wants to select a complex search term (i.e. two or more terms), one first has to close the browser window. A simple example:

```
"window_browser _filters": {
        "added:1": "Alt+Ctrl+1",
	"added:2": "Alt+Ctrl+2",
        "added:1 card:1": "Alt+Crtl+3"
}
```

Another useful addition would be if the search terms were added to what is currently in the search box (instead of replacing everything).

Thank you as always!

**Comment by Liresol** [comment]
So I just pushed out an update to have concatenation as an option for new filter terms.

Adding a filter under the `"_concat"` subobject of `"_filters"` lets you concatenate filters, and adding a filter under `"_orConcat"` lets you concatenate with "or" (which acts as logical or).

As a side note, this is actually one of those invisible features of Anki that I'm not sure anyone knows about. If you hold "Ctrl" while selecting a filter, it gets concatenated. If you hold "Shift", it gets concatenated with "or", and if you hold "Alt", it gets negated (I didn't implement the last one since negation is just `"-filter"` instead of `"filter"`).

**Comment by schmidhauser** [comment]
Great. Many thanks. I love the new concat option.

If anyone else wants to give it a quick try, here's a slightly expanded version of the simple example from above:

```
    "window_browser _filters": {
        "-flag:0": "Alt+Ctrl+0",
        "_concat": {
            "card:1": "Alt+Ctrl+c"
        },
        "added:1": "Alt+Ctrl+1",
        "added:2": "Alt+Ctrl+2"
    },
```
