### ISSUE TITLE
Conflicts with Cloze Overlapper, Enhanced Cloze, and other add-ons that modify Editor.onCloze

### ISSUE THREAD

**Issue by glutanimate** [Liresol/anki-custom-shortcuts#77]
Hey Liresol,

First of all: Really nice work on this add-on, and on steadily improving it with new updates!

Unfortunately the last update had the side-effect of breaking Cloze Overlapper, Enhanced Cloze, and other add-ons that monkey-patch `Editor.onCloze`. It seems like this was introduced by [this commit](https://github.com/Liresol/anki-custom-shortcuts/commit/daa0edc0e0054eec746d90a73843db910fedaabf), specifically, which unbound `Editor.onCloze` in favor of an implementation specific to Customize Keyboard Shortcuts.

As this change is hard to work around in other add-ons without relying on some unstable hacks, I'd really appreciate it if we could find a way to fix this on CKS' side. As both CKS and Cloze Overlapper are fairly popular, it seems like quite a few users are affected (at least judging by all the bug reports I received) and would like to continue using both add-ons if possible.

Thanks again!

**Comment by Liresol** [comment]
The reason for all the weirdness with the cloze shortcut is because of my insistence on having the shortcuts behave exactly as described (which in this case is a fiddly detail regarding the `Alt` key). 
I don't really see a good way to keep this behavior without either seriously changing `Editor.onCloze`, so the change I'm making for the time being is to give up perfect control over `editor cloze` and `editor cloze alt` (i.e. letting both of those just call `Editor.onCloze`) since people probably wouldn't notice the difference.
In case anyone specifically wants the original behavior with their cloze shortcut, I've moved those to `editor cloze forced increment` and `editor cloze no increment` which correspond to the old functions.

Hopefully this should unbreak things, but if it doesn't, let me know and I'll keep working on it.

**Comment by glutanimate** [comment]
Ah, I see why you went with the custom method then. That hard-coded `Alt` detection behavior definitely isn't ideal for reassigning hotkeys freely.

In any case, I just gave the latest dev branch a try and it's working perfectly coupled with Cloze Overlapper. Great job! Really appreciate the lightning-fast response time also. Much appreciated!

**Comment by ccjunior7** [comment]
I found a way around it:
I assigned a key to "editor cloze no increment" (c1,c1,c1...), and another to "editor cloze": (c1,c2,c3...), and left the other ones assignd to "<nop>".
For me, it looks like this now:

    "editor cloze": "F4",
    "editor cloze alt": "<nop>",
    "editor cloze forced increment": "<nop>",
    "editor cloze no increment": "F3",

Sorry for my English.

**Comment by glutanimate** [comment]
@Liresol Thanks again for the fix! It's been working very well over here.

I noticed that this ended up causing quite a few headaches on your end with reviews by confused users and the like. Really sorry about that :/ – AnkiWeb reviews can be super frustrating sometimes. In any case, I really appreciate your going through with the fix, despite the annoyances caused.
