### ISSUE TITLE
Possible to bind mouse buttons?

### ISSUE THREAD

**Issue by harkdand** [Liresol/anki-custom-shortcuts#81]
I would like to use my MOUSE4 and MOUSE5 side buttons for reviewing in anki. Is this possible?

**Comment by Liresol** [comment]
Depending on your mouse/computer, you might be able to rebind those buttons to simulate keyboard presses (e.g. for Windows computers [this might help](https://support.microsoft.com/en-us/help/4052294/accessories-how-do-i-reassign-mouse-buttons)).

At the moment, I don't think raw mouse buttons themselves can be bound, since the underlying code for Anki treats mouse actions differently from keyboard actions.

**Comment by harkdand** [comment]
Thank you!
