### ISSUE TITLE
spacebar mapping

### ISSUE THREAD

**Issue by EliaRouge** [Liresol/anki-custom-shortcuts#82]
I wanted to remap the reviewing "good" key to the right arrow key but the "good" button changes (it's not always 2 or 3) that's what the spacebar is for, it always points at the good button. 
so the question is, can I remap the spacebar?

**Comment by Liresol** [comment]
Hello,
The "flip card" shortcut doubles as answering "good" because of how Anki works, so remapping 
`"reviewer flip card 1": " "` to `"reviewer flip card 1": "Qt.Key_Right"` should do what you want.

By the way, the other two "reviewer flip card" shortcuts do the same thing, so if you want to keep the arrow key you could remap those instead.

**Comment by EliaRouge** [comment]
tysm!!!
