### ISSUE TITLE
Cannot use key '7' in reviewer

### ISSUE THREAD

**Issue by GuitarTab** [Liresol/anki-custom-shortcuts#85]
After update of 2020-11-17, pressing key '7' no longer does what it did before.

Within the Add-On 'More Answer Buttons for New Cards', the keys 7,8,9,0 have been mapped to the additional buttons, that appear in the reviewer.

Keys 8,9,0 still work, but key '7' does not.

The default is changed as follows:

`"reviewer seek forward": "<nop>",`

but now, after the update, this seems to be ignored.

PS: Feature Idea:
It would be very useful if all changes, i.e. everything that has been changed from the defaults, were displayed in a *different color* …
I do not really remember what I changed in the past; how is my workflow affected if I'd have to disable the Add-On …

**Comment by Liresol** [comment]
Hello,
I have just pushed out an update to hopefully patch the shortcut issue, sorry for any inconvenience.

As for the idea of highlighting the shortcut changes, I agree that improving how the shortcut changes are displayed would help. Unfortunately, this feature would probably require a lot of work and right now I don't have too much time to dedicate to something with that large a scope. 
Hopefully I will be able to address it at some point, but it will likely be later rather than sooner.

**Comment by GuitarTab** [comment]
Thanks; greatly appreciated!

As for documenting one's own edits:
Is it possible to **add comments** after each line in the config file?

like

`<!-- comment -->` or
`/* comment */`

**Comment by Liresol** [comment]
Due to the way that configs work right now, you can actually add your own fields that contain information but don't do anything.

So you could enter elements into the config like `"__comments": "comments",...` and Anki will save those without affecting any shortcuts
