### ISSUE TITLE
Indent outdent

### ISSUE THREAD

**Issue by bleda3** [Liresol/anki-custom-shortcuts#97]
Hey, Thanks for your Addon! I hope, that in a few months, after learning some pyhton, I can support it.

Id like to create an shortcut for indent and outdent (cf this foto (https://imgur.com/a/AoTBUtF) ), so that I don't have to take off my hand from the keyboard, when working with different level of lists. Rhe standard Anki shortcut doesn't work with my keyboard settings.

I tried to create the shortcut on my own like this
```
"editor indent":"Ctrl+Qt.Key_Right",
"editor outdent":"Ctrl+Qt.Key_Left",
```
but didn't even manage to add a simple sample shortcut:
If I add it here 
```
{
    "editor _duplicates": {
    "editor indent":"Ctrl+7", 
}
    "editor _extras": {
        "paste custom text": "<nop>"
   }, 
```
I get the error message
> not valid configuration: JSONDecodeError('Expecting property name enclosed in double quotes: line 4 column 1 (char 61)')

But I get almost the same error message if I use egs. the term _bold_ 

If I post my test code `"editor indent":"Ctrl+7",` somewhere else it doesn't send.

**My questions**

1. Is my code technically placed correctly within the {Brackets} after "editor _duplicates"?
2. Where do I find this json file to which the readme is refering (I checked the anki and the addons folder.) 
> All the keywords are exactly the same as the keywords used in the json file, making the lines copy-pastable. 
3. Whats the solution to get an ident and outdent via` Ctrl+Arrow.left` / `Ctrl+Arrow.right`?

edit: first git-hub post ever!

**Comment by Liresol** [comment]
Hello,
Welcome to Github! Working with addons can be weird at times, but it can also be really rewarding when everything works the way you want it. Anyway, here is what I have for your questions:

1. The name is placed correctly in editor duplicates, and the error that Anki is complaining about is actually that you had an extra comma after the string you put (`"editor indent":"Ctrl+7"` vs. ` "editor indent":"Ctrl+7",`). If you remove the extra comma, then the setting would probably be okay (though it might not do anything).

2. The main JSON files used in most addons are named `config.json`, and they are usually the things you mess with if you want to change the config of an addon. For example, on this Github page you can find the current default config file [here](https://github.com/Liresol/anki-custom-shortcuts/blob/dev/custom_shortcuts/config.json) and if you have any other addons then those config files might would also be JSON files. 

3. In order to make the shortcuts in the config file work in the app, you would have to find where the indent function's shortcut is and add code that makes the function activate when you press that shortcut. This might require going through Anki's source code (which is [also on Github](https://github.com/ankitects/anki)) or wherever the indent function is implemented. 
For example, the `editor bold` value in the config file is seen by the addon as `config["editor bold"]`. In order to change the actual function to be that value, you would find the original place where that shortcut is set ([which is here](https://github.com/ankitects/anki/blob/3a250f523855856fec7f884f6d45f42134749bea/qt/aqt/editor.py#L334)) and replaces it with a similar line with the user's shortcut ([which is here](https://github.com/Liresol/anki-custom-shortcuts/blob/551efb746ebe9d7d2c9d1e4d2a8c30001189e74c/custom_shortcuts/custom_shortcuts.py#L182)). There are more details due to shortcut duplication and the handling of things like the arrow keys, but that's the basic idea of what's going on behind the scenes for shortcuts. 
I actually don't currently know about Anki's indent/outdent functions, and they might be part of another addon. If this is the case, you might have to check which addon does this and work with that addon instead.

Hope this helps!

**Comment by bleda3** [comment]
Thank you for your quick reply and your prep talk :+1:  

1. Anki stopped complaining. Thanks.
2. So your Addon-Editor shows a limited part of the .json file and changes the .json file after saving?
3. True. indent is implemented via the "Mini Format Pack" addon (https://ankiweb.net/shared/info/295889520) Seems like I need to learn some more python __after__ my exam next week :) but I am going to check in the Mini Format Pack if I can change the shortcut there.

you may close the issue if you want. however, I may post the solution one day.

thanks again and see you around.

**Comment by Liresol** [comment]
So the details with config files is a little more complicated, namely that whenever you save the modified config file, it actually saves a different json file named `meta.json` (which you can see by looking at the files when you clock "View Files" on an addon). 

By the way, in case you haven't seen it already, [Anki has a short guide for building addons](https://addon-docs.ankiweb.net/#/). There are some details that it doesn't completely cover, but it covers a lot of the tools and patterns that you might see when working on addons.

I'm going to close the issue now, but you are still free to post the solution whenever it arrives, since info on closed issues is still useful for helping people.
